### ISSUE TITLE
The key of frantic1048 seems to be missing on the default keyserver

### ISSUE THREAD

**Issue by ljxfstorm** [archlinuxcn/archlinuxcn-keyring#11]
Error raised when installing archlinuxcn-keyring setting up a new VPS.

> % sudo pacman -S archlinuxcn-keyring
> resolving dependencies...
> looking for conflicting packages...
> 
> Packages (1) archlinuxcn-keyring-20170517-1
> 
> Total Installed Size:  0.11 MiB
> 
> :: Proceed with installation? [Y/n] y
> (1/1) checking keys in keyring                                                                                               [###########################################################################] 100%
> (1/1) checking package integrity                                                                                             [###########################################################################] 100%
> (1/1) loading package files                                                                                                  [###########################################################################] 100%
> (1/1) checking for file conflicts                                                                                            [###########################################################################] 100%
> (1/1) checking available disk space                                                                                          [###########################################################################] 100%
> :: Processing package changes...
> (1/1) installing archlinuxcn-keyring                                                                                         [###########################################################################] 100%
> ==> Appending keys from archlinuxcn.gpg...
> ==> Locally signing trusted keys in keyring...
>   -> Locally signing key 5984EA8F3C6C92945EB2EE40BE378C0A19C6421B...
>   -> Locally signing key 7028E1F320C45EE98473B1C35F1BC1A1BF2B11D0...
>   -> Locally signing key F905932C85D705FD2A3CC9E47C63370395FF0792...
>   -> Locally signing key C7C94A10985C93D4A9141594D9458EF92FE6A447...
>   -> Locally signing key F357BC80BE28C292B40ECEC8997995DF61A0959A...
>   -> Locally signing key 243C14E5339E1B88EDCB29C595FC83B3084A5ADD...
>   -> Locally signing key D2DE8CCA1E74D572369F4C699207632BD48BDDAA...
> ==> ERROR: D2DE8CCA1E74D572369F4C699207632BD48BDDAA could not be locally signed.
>   -> Locally signing key D88390B2991F8242FABD2A3C07F45E2A1937DD32...
>   -> Locally signing key 4FAE5F3EFB9ADABEE8753427A87A225CA0B4B1A4...
>   -> Locally signing key AA0CBF3859E580B97D9F04638FDE3D8FC99F40AE...
>   -> Locally signing key 70522E06662E87A6024E6A6EA22A42A4BA266106...
>   -> Locally signing key 00e716120987a801cd25070828d10c49a44f261e...
>   -> Locally signing key 9BE836747F3533EAABA99F1485AEA2926167AD32...
>   -> Locally signing key 4CFF42599833CF3AE98A2F098850CBC20940E3F9...
>   -> Locally signing key 0285FB6900D102030550F20A34908FFBC0BFAC35...
>   -> Locally signing key 02E02B85AF209AA00F784A1DD48313B447CD9E46...
>   -> Locally signing key 86EEEC214D245137446F4AB195304B04071CCDB4...
>   -> Locally signing key 356690A1E7404E30D0E902B2E64D049594A54F54...
>   -> Locally signing key 4BA7F3CFC2A762CE8D45FFA736C2D41250A009D5...
>   -> Locally signing key B5971F2C5C10A9A08C60030F786C63F330D7CB92...
>   -> Locally signing key 83F817213361BF5F02E7E124F9F9FA97A403F63E...
>   -> Locally signing key CF3271E49632068A5DCA9316719D54FFDDD310E2...
>   -> Locally signing key 708DFB13CBED9AB39449DBFB41C04120C297B594...
>   -> Locally signing key 2AC4CFDB42972D38F105800BC0EB1AA4536A8318...
>   -> Locally signing key 1B53ED6B05A88B45FE02AE6186CC4303D870877E...
>   -> Locally signing key 4B1DE545A801D4549BFD3FEF90CB3D62C13D4796...
>   -> Locally signing key CF73A9AE20AD483CE51130E0303A369BE11E4BE7...
> ==> Updating trust database...
> gpg: marginals needed: 3  completes needed: 1  trust model: pgp
> gpg: public key CF66D153D884358F is 16 seconds newer than the signature
> gpg: depth: 0  valid:   1  signed:  30  trust: 0-, 0q, 0n, 0m, 0f, 1u
> gpg: depth: 1  valid:  30  signed:  71  trust: 25-, 0q, 0n, 5m, 0f, 0u
> gpg: depth: 2  valid:  68  signed:  10  trust: 68-, 0q, 0n, 0m, 0f, 0u
> gpg: next trustdb check due at 2017-08-24
> :: Running post-transaction hooks...
> (1/1) Arming ConditionNeedsUpdate...

Tried to manually sign the key

> % sudo pacman-key -r D2DE8CCA1E74D572369F4C699207632BD48BDDAA
> gpg: no valid OpenPGP data found.
> gpg: Total number processed: 0
> ==> ERROR: Remote key not fetched correctly from keyserver.

Here is my keyserver config for pacman-key

> % cat /etc/pacman.d/gnupg/gpg.conf
> no-greeting
> no-permission-warning
> lock-never
> keyserver hkp://pool.sks-keyservers.net
> keyserver-options timeout=10

Found out the info of the key on my PC.

> % sudo pacman-key -f D2DE8CCA1E74D572369F4C699207632BD48BDDAA
> pub   ed25519 2017-01-05 [C]
>       D2DE 8CCA 1E74 D572 369F  4C69 9207 632B D48B DDAA
> uid           [  full  ] frantic1048 (shorthand for archer@frantic1048.com) <i@frantic1048.com>
> sub   rsa2048 2017-01-05 [E] [expires: 2020-01-05]
> sub   rsa2048 2017-01-05 [S] [expires: 2020-01-05]
> sub   rsa2048 2017-01-05 [A] [expires: 2020-01-05]

It worked fine when updating the installed archlinuxcn-keyring pack on my PC, but manually signing failed as well.

**Comment by lilydjwg** [comment]
@frantic1048

**Comment by lilydjwg** [comment]
This key is on server, verifiable by `gpg --keyserver hkp://pool.sks-keyservers.net --search D2DE8CCA1E74D572369F4C699207632BD48BDDAA`. There might be issues with the server when you tried, or with your dirmngr process.

To sign it locally, use `sudo pacman-key --lsign D2DE8CCA1E74D572369F4C699207632BD48BDDAA`.

**Comment by ljxfstorm** [comment]
I've tried again, and "sudo pacman-key -r $keyid" worked.
Might be issues with the server at that time.
Thanks.

**Comment by frantic1048** [comment]
Could you paste the out put of `gpg --version` on your VPS ?

**Comment by ljxfstorm** [comment]
> % sudo gpg --version
> gpg (GnuPG) 2.1.21
> libgcrypt 1.7.6
> Copyright (C) 2017 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> 
> Home: /root/.gnupg
> Supported algorithms:
> Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
> Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
>         CAMELLIA128, CAMELLIA192, CAMELLIA256
> Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
> Compression: Uncompressed, ZIP, ZLIB, BZIP2

**Comment by farseerfc** [comment]
Current version of gpg seems good.
May I ask, did you update gpg after seeing the error?
What was the version of gpg that producing this error?

**Comment by ljxfstorm** [comment]
My mistake. A daily rolling update happened after that.
I'm trying to restore a snapshot to reproduce.

**Comment by ljxfstorm** [comment]
Restored the VPS snapshot and reproduced the "could not be locally signed" error.

> % sudo pacman -S archlinuxcn-keyring
> warning: archlinuxcn-keyring-20170517-1 is up to date -- reinstalling
> resolving dependencies...
> looking for conflicting packages...
> 
> Packages (1) archlinuxcn-keyring-20170517-1
> 
> Total Installed Size:  0.11 MiB
> Net Upgrade Size:      0.00 MiB
> 
> :: Proceed with installation? [Y/n] y
> (1/1) checking keys in keyring                                                                                               [###########################################################################] 100%
> (1/1) checking package integrity                                                                                             [###########################################################################] 100%
> (1/1) loading package files                                                                                                  [###########################################################################] 100%
> (1/1) checking for file conflicts                                                                                            [###########################################################################] 100%
> (1/1) checking available disk space                                                                                          [###########################################################################] 100%
> :: Processing package changes...
> (1/1) reinstalling archlinuxcn-keyring                                                                                       [###########################################################################] 100%
> ==> Appending keys from archlinuxcn.gpg...
> ==> Locally signing trusted keys in keyring...
>   -> Locally signing key 5984EA8F3C6C92945EB2EE40BE378C0A19C6421B...
>   -> Locally signing key 7028E1F320C45EE98473B1C35F1BC1A1BF2B11D0...
>   -> Locally signing key F905932C85D705FD2A3CC9E47C63370395FF0792...
>   -> Locally signing key C7C94A10985C93D4A9141594D9458EF92FE6A447...
>   -> Locally signing key F357BC80BE28C292B40ECEC8997995DF61A0959A...
>   -> Locally signing key 243C14E5339E1B88EDCB29C595FC83B3084A5ADD...
>   -> Locally signing key D2DE8CCA1E74D572369F4C699207632BD48BDDAA...
> ==> ERROR: D2DE8CCA1E74D572369F4C699207632BD48BDDAA could not be locally signed.
>   -> Locally signing key D88390B2991F8242FABD2A3C07F45E2A1937DD32...
>   -> Locally signing key 4FAE5F3EFB9ADABEE8753427A87A225CA0B4B1A4...
>   -> Locally signing key AA0CBF3859E580B97D9F04638FDE3D8FC99F40AE...
>   -> Locally signing key 70522E06662E87A6024E6A6EA22A42A4BA266106...
>   -> Locally signing key 00e716120987a801cd25070828d10c49a44f261e...
>   -> Locally signing key 9BE836747F3533EAABA99F1485AEA2926167AD32...
>   -> Locally signing key 4CFF42599833CF3AE98A2F098850CBC20940E3F9...
>   -> Locally signing key 0285FB6900D102030550F20A34908FFBC0BFAC35...
>   -> Locally signing key 02E02B85AF209AA00F784A1DD48313B447CD9E46...
>   -> Locally signing key 86EEEC214D245137446F4AB195304B04071CCDB4...
>   -> Locally signing key 356690A1E7404E30D0E902B2E64D049594A54F54...
>   -> Locally signing key 4BA7F3CFC2A762CE8D45FFA736C2D41250A009D5...
>   -> Locally signing key B5971F2C5C10A9A08C60030F786C63F330D7CB92...
>   -> Locally signing key 83F817213361BF5F02E7E124F9F9FA97A403F63E...
>   -> Locally signing key CF3271E49632068A5DCA9316719D54FFDDD310E2...
>   -> Locally signing key 708DFB13CBED9AB39449DBFB41C04120C297B594...
>   -> Locally signing key 2AC4CFDB42972D38F105800BC0EB1AA4536A8318...
>   -> Locally signing key 1B53ED6B05A88B45FE02AE6186CC4303D870877E...
>   -> Locally signing key 4B1DE545A801D4549BFD3FEF90CB3D62C13D4796...
>   -> Locally signing key CF73A9AE20AD483CE51130E0303A369BE11E4BE7...
> ==> Updating trust database...
> gpg: marginals needed: 3  completes needed: 1  trust model: pgp
> gpg: public key CF66D153D884358F is 16 seconds newer than the signature
> gpg: depth: 0  valid:   1  signed:  30  trust: 0-, 0q, 0n, 0m, 0f, 1u
> gpg: depth: 1  valid:  30  signed:  71  trust: 25-, 0q, 0n, 5m, 0f, 0u
> gpg: depth: 2  valid:  68  signed:  10  trust: 68-, 0q, 0n, 0m, 0f, 0u
> gpg: next trustdb check due at 2017-08-24
> :: Running post-transaction hooks...
> (1/1) Arming ConditionNeedsUpdate...

However, gpg --version ouputs the same.

> % sudo gpg --version
> gpg (GnuPG) 2.1.21
> libgcrypt 1.7.6
> Copyright (C) 2017 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> 
> Home: /root/.gnupg
> Supported algorithms:
> Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
> Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
>         CAMELLIA128, CAMELLIA192, CAMELLIA256
> Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
> Compression: Uncompressed, ZIP, ZLIB, BZIP2

**Comment by ljxfstorm** [comment]
The output of pacman-key -r changed.
Here's some info.

> % sudo pacman-key --lsign D2DE8CCA1E74D572369F4C699207632BD48BDDAA
>   -> Locally signing key D2DE8CCA1E74D572369F4C699207632BD48BDDAA...
> ==> ERROR: D2DE8CCA1E74D572369F4C699207632BD48BDDAA could not be locally signed.
> % sudo pacman-key -f D2DE8CCA1E74D572369F4C699207632BD48BDDAA
> gpg: error reading key: No public key
> ==> ERROR: The fingerprint of a specified key could not be determined.
> % sudo pacman-key -r D2DE8CCA1E74D572369F4C699207632BD48BDDAA
> .gpg: keyserver receive failed: No data
> ==> ERROR: Remote key not fetched correctly from keyserver.
> % cat /etc/pacman.d/gnupg/gpg.conf
> no-greeting
> no-permission-warning
> lock-never
> keyserver hkp://pool.sks-keyservers.net
> keyserver-options timeout=10
> % ping pool.sks-keyservers.net
> PING pool.sks-keyservers.net (83.149.68.11) 56(84) bytes of data.
> 64 bytes from srv01.secure-u.de (83.149.68.11): icmp_seq=1 ttl=53 time=110 ms
> 64 bytes from srv01.secure-u.de (83.149.68.11): icmp_seq=2 ttl=53 time=110 ms
> 64 bytes from srv01.secure-u.de (83.149.68.11): icmp_seq=3 ttl=53 time=110 ms
> ^C
> --- pool.sks-keyservers.net ping statistics ---
> 3 packets transmitted, 3 received, 0% packet loss, time 2001ms
> rtt min/avg/max/mdev = 110.567/110.589/110.612/0.384 ms

**Comment by ljxfstorm** [comment]
gpg --search worked fine.

> % gpg --keyserver hkp://pool.sks-keyservers.net --search D2DE8CCA1E74D572369F4C699207632BD48BDDAA
> gpg: data source: http://69.31.184.214:11371
> (1)     frantic1048 <archer@frantic1048>
>         frantic1048 <archer@frantic1048.com>
>         Jiahao Guo (school issued mailbox) <frantichao@bit.edu.cn>
>         frantic1048 (Arch Linux CN Community) <frantic1048@archlinuxcn.org>
>         frantic1048 (shorthand for archer@frantic1048.com) <i@frantic1048.com>
>           256 bit EDDSA key 9207632BD48BDDAA, created: 2017-01-05
> Keys 1-1 of 1 for "D2DE8CCA1E74D572369F4C699207632BD48BDDAA".  Enter number(s), N)ext, or Q)uit > N

**Comment by ljxfstorm** [comment]
Just updated the archlinuxcn-keyring-20170522-1, and no error rasied.
But the `pacman-key -r D2DE8CCA1E74D572369F4C699207632BD48BDDAA` is still not working well.

**Comment by ljxfstorm** [comment]
Try to reset all the keys by removing `/etc/pacman.d/gnupg` and `pacman-key --init`.
And `pacman-key -r D2DE8CCA1E74D572369F4C699207632BD48BDDAA` worked then.
If anyone wants to reproduce the issue, I can restore the snapshot.

**Comment by farseerfc** [comment]
Can you send me a tarball of `/etc/pacman.d/gnupg` that can reproduce this error?
This directory contains your local signing key pair for your system. You can generate a new key pair after that by `pacman-key --init` which effectively revoke the old key pair.
If this is OK for you, please send the tarball to farseerfc@archlinuxcn.org , I will look into it when I have time. Thank you.

**Comment by ljxfstorm** [comment]
Sent.
Reinstalling archlinuxcn-keyring-20170517-1 or manually `pacman-key --lsign $keyid` will reproduce the "could not be locally signed" error.
However, manually `pacman-key -r $keyid` worked this time, which is really weird that this operation turned out three different outputs.
