### ISSUE TITLE
My new gpg key

### ISSUE THREAD

**Issue by SilverRainZ** [archlinuxcn/archlinuxcn-keyring#12]
My old key `4BA7F3CFC2A762CE8D45FFA736C2D41250A009D5` will be expired soon (2017.8.24) and deprecated.

Here is the fingerprint of my new key: `99399D88F7B752BF364CD485A85E3925A6211F05`.

**Comment by SilverRainZ** [comment]
@farseerfc

**Comment by farseerfc** [comment]
done in 98e0083d800ad4270d931be04320e33efef9c38b
