### ISSUE TITLE
error: key could not be locally signed

### ISSUE THREAD

**Issue by IceDragen** [archlinuxcn/archlinuxcn-keyring#18]
**ERROR: 1FDBDCE2D26BD8F100EE2E73B1B9AAD8BE7E7326 could not be locally signed.
  -> Locally signing key 5984EA8F3C6C92945EB2EE40BE378C0A19C6421B...**

I have tried with the following instruction:
**rm -rf /etc/pacman.d/gnupg
pacman-key --init
pacman-key --populate archlinux manjaro && pacman-key --populate archlinuxcn**

but it's still not worked.

**Comment by kmahyyg** [comment]
gpg: key 786C63F330D7CB92: no user ID for key signature packet of class 10
gpg: public key CF66D153D884358F is 16 seconds newer than the signature

**Comment by farseerfc** [comment]
Can you please try whether 20190729 fixed this problem?

**Comment by kmahyyg** [comment]
Fixed.

**Comment by tianheg** [comment]
met this error again

```sh
gpg: key 786C63F330D7CB92: no user ID for key signature packet of class 10
gpg: key 1EB2638FF56C0C53: no user ID for key signature packet of class 10
```
