### ISSUE TITLE
issue with gpg

### ISSUE THREAD

**Issue by SolarAquarion** [archlinuxcn/archlinuxcn-keyring#2]
:: Proceed with installation? [Y/n] y
:: Retrieving packages ...
 chromium-dev-48.0.2...    44.9 MiB  4.27M/s 00:11 [######################] 100%
(1/1) checking keys in keyring                     [######################] 100%
downloading required keys...
error: key "85AEA2926167AD32" could not be looked up remotely
error: required key missing from keyring
error: failed to commit transaction (unexpected error)
Errors occurred, no packages were upgraded.

**Comment by lilydjwg** [comment]
@felixonmars 记得和我的新 [key](https://github.com/lilydjwg/keys) 一起加了～

**Comment by felixonmars** [comment]
Both added.
