### ISSUE TITLE
无法远程查找到密钥 "90CB3D62C13D4796"

### ISSUE THREAD

**Issue by zhaoyufei11011** [archlinuxcn/archlinuxcn-keyring#20]
[root@archlinux packages]#  pacman -S archlinuxcn-keyring
正在解析依赖关系...
正在查找软件包冲突...

软件包 (1) archlinuxcn-keyring-20191026-1

全部安装大小：  0.33 MiB

:: 进行安装吗？ [Y/n] y
(1/1) 正在检查密钥环里的密钥                                                                                       [####################################################################] 100%
正在下载所需的密钥......
:: Import PGP key 90CB3D62C13D4796, "Jiachen YANG <farseerfc@archlinux.org>"? [Y/n] y
错误：无法远程查找到密钥 "90CB3D62C13D4796"
错误：所需的密钥不在密钥环中
错误：无法提交处理 (未预期的错误)
发生错误，没有软件包被更新。

**Comment by farseerfc** [comment]
誒？我的 key 是在 archlinux-keyring 裏面的呀，你的 archlinux-keyring 的版本是？

**Comment by zhaoyufei11011** [comment]
呃 没注意这点 是archlinux-keyring版本的问题

**Comment by farseerfc** [comment]
那麼這個 issue 解決了麼？解決了的話我就 close 掉了
