### ISSUE TITLE
PGP key rotation for PeterCxy

### ISSUE THREAD

**Issue by PeterCxy** [archlinuxcn/archlinuxcn-keyring#25]
Old key: 41C04120C297B594
New key: 4F6F4B73393BE350

Both available from pgp.mit.edu / keyserver.ubuntu.com

Both keys are cross-signed.

**Comment by farseerfc** [comment]
added new key as petercxy2 , should we delete or revoke the old key?
revoking should be used when the old key is lost.

**Comment by PeterCxy** [comment]
@farseerfc The key is not leaked or lost, this is just a regular key rotation. Simply deleting the old key should be good enough.
