### ISSUE TITLE
add key

### ISSUE THREAD

**Issue by ykelvis** [archlinuxcn/archlinuxcn-keyring#5]
Please help me add my key. Thanks.
[yk.txt](https://github.com/archlinuxcn/archlinuxcn-keyring/files/206583/yk.txt)

**Comment by farseerfc** [comment]
Please register this key on a keyserver. 
Our [update-keys](https://github.com/archlinuxcn/archlinuxcn-keyring/blob/master/update-keys) script seems to perfer download these keys from keyserver by itself.

**Comment by ykelvis** [comment]
Uploaded to hkp://pool.sks-keyservers.net .

**Comment by farseerfc** [comment]
Sorry, no keys found
http://pool.sks-keyservers.net/pks/lookup?op=vindex&search=0xF357BC80BE28C292B40ECEC8997995DF61A0959A&fingerprint=on

Is `0xF357BC80BE28C292B40ECEC8997995DF61A0959A` the fingerprint of your key?

**Comment by ykelvis** [comment]
Yes.
`      Key fingerprint = F357 BC80 BE28 C292 B40E  CEC8 9979 95DF 61A0 959A`

**Comment by farseerfc** [comment]
OK, found it (might be sync delay).
