### ISSUE TITLE
Add my key plz

### ISSUE THREAD

**Issue by dxhisboy** [archlinuxcn/archlinuxcn-keyring#6]
I've packaged libxfcegui4, and when I install it from pacman, it shows my key Xiaohui Duan<dxhisboy@gmail.com> is unknown trust.
My public key is:
-----BEGIN PGP PUBLIC KEY BLOCK-----

mQENBFfEUCwBCADbo5PyfaZfZtNkSVjoypvr91RCRxzGaEtUKB/3Ob1CceDb50+G
YiUUhWY/8z0cv7VIo16V86ncIiYYonRDFC9jH87XYpgoaBN4yLU0CEUYunxaqxIv
HAYIJhTKAsSuFYVTIg6ed8nIX/fo2MDlfdBtsDOphRTLTE+ecgwSnX3uUwbdRYtq
Ka4C8a1pWsB10PJt0kBKEAkE+s8DV4Gl2S3PnBlZUffd09kNuMbqmSWRaTChULcO
1UtwTGlk+26lomlaKbRW/bjHjBL7gSmQAFqnmRWKwMD5p2e35rt0cwB4kxYMlhku
FdcwOcA/aVWjs9fKrNvifno9lqF3scOumh2BABEBAAG0IVhpYW9odWkgRHVhbiA8
ZHhoaXNib3lAZ21haWwuY29tPokBNwQTAQgAIQUCV8RQLAIbAwULCQgHAgYVCAkK
CwIEFgIDAQIeAQIXgAAKCRC+N4wKGcZCG6o1CAC4dAASVv2N0eQ63PlxhTyYBSOf
wNTKd0SxkthRQagDeQr7ef3w2qwMx0Kx9Uac+reNmjJhkopH3P1rkIdmIc3oEKyy
6KT0XXIkmisnqayJKSjkC11JR8ZhXuLeySsFucT71aDtU7rMOl0KAjCWdO19XkHZ
WdTvpHEjRbiQGl5nRJ10tgvLBu7IqmDzt7AJyB7B3umFDldh/+UU2lpedbVHLaNL
z95G87Q3ADJLrIjPiBYPo9G7PLqCDpde8P59JglmKwz5EA+zUgvBQTLQ+HEwPVE6
IZA6CJTYCXk8r0mu1ZkyCwZ6cop6KyrTZePjOGwiv21qQENKXPpOZPTydXJ+uQEN
BFfEUCwBCACkixAAiLzwAc9KZw64ZWGCFA/jWxSK+QiUs8nWSoOaKabFCCrs6MNg
/hfoJkHhTV0IZxgFnHZiQn88DG9utZU6SDOokyKTxAuNJOyW+taZM8hJMP1n836r
7EW0kx5Vrf4nZL70xTCsjMY6NOppKSdnU5EpCurlYCBCq77kzr+00tWAZxgy9V/6
2A7NrgNqyY/7ZX1Mti7W07V4imaQ9m8AAiNWjVV8CY6vuW3Jfplvu4d1Z+OXowC3
cOcLH9vlb7A5jl527CbRCTeDxPAtyNvzeWq9RK/TMcI//UQTw1tMH1nAIQPskMPe
pSK874crQmWJ142mwGXq4KBfEXpzSJwTABEBAAGJAR8EGAEIAAkFAlfEUCwCGwwA
CgkQvjeMChnGQhubSwf/ctZicucepCUdysARTyUjAXUEGmGl/nCMAv/BIzr91DuD
VlaOrsQaQqIrVnymAz9KFXWPlfOcPmRUZOIh5IaMdZ2WUx8F2XVwGty9Swm2okJL
uAQtp/VG0vNK6b8ruC2sm3kjzf5sZU7k3MwJl4OvkIgMG7FoxNxSYezj2HyIJTlJ
P3EHkdp7HTtzEQgabIueU+n5PCsF+m/ddvSx187DIW7bLHjQe6+xp0lrESTaJbnF
TGLaKwi0Rk54iAWbxWb9/y0mbv6i3TXeYsWfjtq9+S1ZBK3adadquaiFP4fj+eIn
r0jFjM1NWQ5robKstg8cuumdk7haJuCKNnKw8l9WnA==
=lIG1
-----END PGP PUBLIC KEY BLOCK-----

**Comment by farseerfc** [comment]
As I replied in the mail, please publish the pubkey on one of the PGP key server, our script will retrieve it from the key server only:
https://github.com/archlinuxcn/archlinuxcn-keyring/blob/master/update-keys#L8

**Comment by farseerfc** [comment]
See also #4 #5

**Comment by dxhisboy** [comment]
OK, my key is already present in https://sks-keyservers.net/pks/lookup?op=vindex&search=dxhisboy%40gmail.com, while also available from mit's key server, and what else shall I do?

**Comment by farseerfc** [comment]
archlinuxcn-keyring 20160903 should have your key
