### ISSUE TITLE
减少gpg key的数量

### ISSUE THREAD

**Issue by petronny** [archlinuxcn/archlinuxcn-keyring#7]
我用下面的命令

``````
for i in `pacman -Slq archlinuxcn`;do LANG=C pacman -Si archlinuxcn/$i | grep "Packager" | grep -v 'lilac' ;done | sort | uniq -c | sort -h -r```
统计了一下Packager的种类，去掉了Packager为lilac的部分
剩下的而应该都是手动打包需要gpg key 在archlinuxcn-keyring才能装的
``````

```
 72 Packager        : Felix Yan <felixonmars@archlinux.org>
 61 Packager        : Colin Keenan <colinnkeenan@gmail.com>
 52 Packager        : yk <yk@build.archlinuxcn.org>
 18 Packager        : Felix Yan <felixonmars@gmail.com>
 16 Packager        : Yichao Yu <yyc1992@gmail.com>
 11 Packager        : Zuyi Hu <hzy068808@gmail.com>
  7 Packager        : xduan <xduan@build.archlinuxcn.org>
  7 Packager        : lilydjwg <lilydjwg@gmail.com>
  7 Packager        : Jiachen Yang <farseerfc@gmail.com>
  3 Packager        : renyuneyun <renyuneyun@build.archlinuxcn.org>
  3 Packager        : phoenixlzx <phoenixlzx@archlinuxcn.org>
  3 Packager        : lilydjwg <lilydjwg@build.archlinuxcn.org>
  3 Packager        : fixme <fixme@build.archlinuxcn.org>
  2 Packager        : Unknown Packager
  2 Packager        : renyuneyun <renyuneyun@gmail.com>
  2 Packager        : lastavengers <lastavengers@build.archlinuxcn.org>
  1 Packager        : zsrkmyn <zsrkmyn@build.archlinuxcn.org>
  1 Packager        : gsc <gsc@build.archlinuxcn.org>
```

```
我觉得其实这里面很多包都没有必要手动打包，都交给lilac能减少很多签名问题
```

**Comment by farseerfc** [comment]
Balló György 是誰的簽名？

lilac 的簽名也是在 archlinuxcn-keyring 的，不裝 keyring 的話應該只能裝我和肥貓的包吧。
另外我覺得是否用 lilac 應該是打包者的選擇的自由，有些包可能有理由不用 lilac 。

**Comment by petronny** [comment]
> Balló György 是誰的簽名？

spice-vdagent这个包，和community的重了
Levente Polyak \<anthraxx@archlinux.org\>这个人的也是。。

> lilac 的簽名也是在 archlinuxcn-keyring 的，不裝 keyring 的話應該只能裝我和肥貓的包吧。

keyring肯定得装，里面应该包含lilac和少数必须手动打包的

> 另外我覺得是否用 lilac 應該是打包者的選擇的自由，有些包可能有理由不用 lilac 。

的确有的包最好是手动打包，但是我觉得上面这200多个不可能都是只适合手动打包的，肯定至少有150个可以用lilac解决

PS. 上面的那个命令其实最好用`pacman -Si archlinuxcn/$pkgname`，以避免不同源有同名包的问题

**Comment by zsrkmyn** [comment]
@petronny 其实我个人更赞成手动打包，自动打包的话 packager 是没有办法进行测试就直接推给用户的，有些包虽然打包能成功，但是运行时会出现问题。这样会给用户带来很多麻烦。（这条对于我这样又懒又不负责的打包者不适用
其次，减少打包者/key的数量并不能带来什么便利。
另外我赞同 @farseerfc 的说法，「是否用 lilac 應該是打包者的選擇的自由」，比如 felixonmars 这种以打包为乐趣的猫是不会选择让 lilac 剥夺享乐的权利的 (

**Comment by petronny** [comment]
好吧我了解了

**Comment by lilydjwg** [comment]
是否使用 lilac 一直都是打包者的自由啊。只有不属于打包者团队的人（提 pr）才必须通过 lilac 来打包。

另外可以考虑增加 staging 仓库，可选让 lilac 打的包先进入 staging 环境，然后再手动移到正式环境。

**Comment by zsrkmyn** [comment]
official repo的 staging 或者 testing 是怎么个工作流程？感觉一个 packager
手下这么多包，并不是每个包都来得及测试的呀～

2017年1月3日 上午10:59，"依云" <notifications@github.com>写道：

**Comment by farseerfc** [comment]
staging 是用來處理 rebuild 的。比如 A 依賴 B ， B 更新版本打包會破壞 A 的兼容性，那麼先針對 extra/testing 打包 B 推到 staging ，然後針對 staging 打包所有依賴 B 的都推到 staging ，然後用腳本一起從 staging 裏放出到 extra/testing 。所以 staging 裏的包都完全沒測過，開 staging 很可能破壞包依賴關係。
core 和 extra 的區別在於是否強制要求 signoff 。 core 的包都必須先在 testing 裏，然後有足夠的 signoff 之後就可以放出來，也是腳本一起移動。
community 和 extra 的區別在有提交權限的人不一樣，所以 community 有單獨的 community-testing 和 community-staging ，別的和 extra 差不多。
core 強制要求 signoff 所以會有打包者之外的人測試， extra/community 是否測試就看良心了，不過基於責任一般版本更新還是會測一下。一般在推往 extra/testing 之前就會本地裝上測一下，再往 extra/testing 推。

參考 https://wiki.archlinux.org/index.php/DeveloperWiki:CoreSignoffs
https://wiki.archlinux.org/index.php/DeveloperWiki:HOWTO_Be_A_Packager

覺得如果 CN 源能有 testing 和 staging 會方便一些。比如這次 python3.6 的包在官方源的 testing ，會牽扯幾個 CN 源的包，目前我們得等他們進入 extra 纔能修，會慢一拍。如果 CN 有 testing ，可以讓 CN 的 testing 跟着官方源的節奏，先把 python 3.6 break 的東西在 testing 修好，然後 python 3.6 進 extra 的時候就會從容一點，移動包就可以了。
不過除了目前的打包工具我們還需要官方源移動包的腳本。

**Comment by lilydjwg** [comment]
@zsrkmyn 指定哪些要走测试流程嘛。比如 linux-lily。
@farseerfc 感觉要把这些东西做好，工作量好大……

**Comment by lilydjwg** [comment]
@zsrkmyn 另外你可以写 check 函数的喵。
仓库里会保留最近两个版本，也是为了方便用户遇到坏包能够降级。

**Comment by zsrkmyn** [comment]
@lilydjwg, 嗯呐，昨天已经开始这样做了，然而研究了一下午没能把 YCM 的 Unit Test 跑通……
@farseerfc, wow 看起来好复杂，总之我没良心就对了……果然一个完善的系统确实好复杂啊，如果能搬到社区源就好了。不过工作量确实很大啊……
